# Generated by Django 5.0.5 on 2024-05-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faketter', '0003_profile_date_modify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_modify',
            new_name='date_modified',
        ),
    ]
