# Generated by Django 5.0.5 on 2024-05-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faketter', '0006_rename_feeks_feek'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
