# Generated by Django 5.0.5 on 2024-05-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faketter', '0007_profile_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='profile_image',
        ),
    ]
