# Generated by Django 5.0.5 on 2024-05-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faketter', '0008_rename_profile_img_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
