# Generated by Django 5.0.5 on 2024-06-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faketter', '0011_profile_facebook_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
